-- ============================================================
-- Gold Analytics - Database Schema (PostgreSQL)
-- ============================================================
-- Note: all domain tables live in their own schemas.
-- See data_sources/<name>/schema.sql for each source.
